[package]
name = "axion-driver"
version.workspace = true
edition.workspace = true

[dependencies]
axion-syntax = { path = "../axion-syntax" }
axion-diagnostics = { path = "../axion-diagnostics" }
axion-lexer = { path = "../axion-lexer" }
axion-parser = { path = "../axion-parser" }
axion-resolve = { path = "../axion-resolve" }
axion-types = { path = "../axion-types" }
axion-module = { path = "../axion-module" }
axion-borrow = { path = "../axion-borrow" }
axion-mono = { path = "../axion-mono" }
axion-codegen = { path = "../axion-codegen" }
serde_json = { workspace = true }
