[package]
name = "axion-types"
version.workspace = true
edition.workspace = true

[dependencies]
axion-syntax = { path = "../axion-syntax" }
axion-diagnostics = { path = "../axion-diagnostics" }
axion-resolve = { path = "../axion-resolve" }

[dev-dependencies]
axion-parser = { path = "../axion-parser" }
