[package]
name = "axion-resolve"
version.workspace = true
edition.workspace = true

[dependencies]
axion-syntax = { path = "../axion-syntax" }
axion-diagnostics = { path = "../axion-diagnostics" }
axion-parser = { path = "../axion-parser" }

[dev-dependencies]
